/*TRANSACTIONS*/
SELECT * FROM EMPLOYEEE;


DELETE EMPLOYEEE
WHERE EMPID=7;
ROLLBACK;
UPDATE EMPLOYEEE
SET FIRSTNAME= 'ATOM'
WHERE EMPID=6;
COMMIT;
UPDATE EMPLOYEEE
SET FIRSTNAME= 'TUKA'
WHERE EMPID=5;
ROLLBACK;